INSERT INTO tnm_guide_resource(name,url,local,category,image) VALUES
	('arakatherine.ceramics','https://www.instagram.com/arakatherine.ceramics/','Houston','',''),
	('Tablada','https://www.instagram.com/tienda.tablada/','Buenos Aires','',''),
	('Auca Estudio','https://www.instagram.com/aucaestudio/','Buenos Aires','',''),
	('Gaias Candy','https://www.instagram.com/gaiascandy/','Berlin','',''),
	('Marion Graux','https://www.instagram.com/mariongrauxpoterie/','Paris','',''),
	('B.Grounded Alstonville','https://www.instagram.com/b.grounded/','Alstonville','',''),
	('Studio Manual','https://www.instagram.com/studio.manual/','Rio de Janeiro','',''),
	('Arvoredo','https://www.instagram.com/arvoredojoias/','Rio de Janeiro','',''),
	('Fast Foward Design','https://www.instagram.com/fastforwarddesign/','Rio de Janeiro','',''),
	('Neumanns Cafe','https://www.instagram.com/neumanns.cafe/','Berlin','',''),
	('Birgit Blau','https://www.instagram.com/birgitblau/','Berlin','',''),
	('Project Object','https://www.instagram.com/projectobject.co/','Portland','',''),
	('Klai','https://www.instagram.com/helloklai/','Los Angeles','',''),
	('Stonedware Company','https://www.instagram.com/stonedwarecompany/','Portland','',''),
	('Realm','https://www.instagram.com/shoprealm/','Austin','',''),
	('Upper Metal Class','https://www.instagram.com/uppermetalclass/','Portland','',''),
	('Oh Me','https://www.instagram.com/ohme_shop/','Seattle','',''),
	('Moon Kid','https://www.instagram.com/moonkidjewellerydesign/','Berlin','',''),
	('Juliana Buli','https://www.instagram.com/julibuliestudio/','','',''),
	('Fach Frau','https://www.instagram.com/fachfrau_berlin/','Berlin','',''),
	('Vida feita à Mão','https://www.instagram.com/vidafeitaamao/','Curitiba','',''),
	('2P Ateliê','https://www.instagram.com/2patelie/','Rio de Janeiro','',''),
	('ODA Design Club','https://www.instagram.com/odadesignclub/','','',''),
	('Trine Fournais Ceramics','https://www.instagram.com/trinefournaisceramics/','Copenhagen','',''),
	('Heidi & bjarne','https://www.instagram.com/heidiogbjarne/','Copenhagen','',''),
	('FLUX - a jewellery collective','https://www.instagram.com/fluxjewellery/','Copenhagen','',''),
	('Nos Lunares','https://www.instagram.com/noslunares/','São Paulo','',''),
	('Leu','https://www.instagram.com/leuceramics/','London','',''),
	('Clay Pool','https://www.instagram.com/claypoolgroup/','Sydney','',''),
	('Cerami.K','https://www.instagram.com/cerami.k_/','Rio de Janeiro','',''),
	('Caitlin Blevins','https://www.instagram.com/caitlinlblevins/','Corvallis','',''),
	('Scout and Arrow','https://www.instagram.com/scoutandarrow_/','Atlanta','',''),
	('Merritt Ceramics','https://www.instagram.com/merrittceramics/','Oakland','',''),
	('LAU','https://www.instagram.com/laureanne_kootstra/','Berlin','',''),
	('Berlin Kreativ Kollektiv','https://www.instagram.com/berlinkreativkollektiv/','Berlin','',''),
	('URSA','https://www.instagram.com/shopursa/','Milwaukee','',''),
	('Hartmund','https://www.instagram.com/hartmudstudio/','Frankfurt','',''),
	('Pompom Project','https://www.instagram.com/pompom.project/','São Paulo','',''),
	('Grato','https://www.instagram.com/grato.design/','Rio de Janeiro','',''),
	('Ocre Cerâmica','https://www.instagram.com/ocreceramica/','São Paulo','',''),
	('Tororó','https://www.instagram.com/tororo_loja/','São Paulo','',''),
	('Mo & Mum','https://www.instagram.com/moandmum/','Berlin','',''),
	('Bruno Paciello','https://www.instagram.com/brunopaciellodesign/','Rio de Janeiro','',''),
	('Jars of dust','https://www.instagram.com/jars.of.dust/','Virginia Beach','',''),
	('María Hernández | Ma-Rya','https://www.instagram.com/by.marya/','Salamanca','',''),
	('Julie Damhus','https://www.instagram.com/damhus/','AARHUS','',''),
	('kate beardmore','https://www.instagram.com/tuskandtwine/','Stafford','',''),
	('Halsion Collective','https://www.instagram.com/halsioncollective/','Vancouver','',''),
	('Greater Goods','https://www.instagram.com/greatergoodsyyc/','Calgary','',''),
	('Magma Lab','https://www.instagram.com/ateliermagmalab/','Rio de Janeiro','',''),
	('imperfecto iotti','https://www.instagram.com/imperfectoiotti/','Buenos Aires','',''),
	('Sarah Bain','https://www.instagram.com/throwingmudetc/','','',''),
	('Peter Montgomery','https://www.instagram.com/petermontgomery/','Devon','',''),
	('Pawena Thimaporn','https://www.instagram.com/pawenastudio/','Los Angeles','',''),
	('Helen Lee Ceramics','https://www.instagram.com/helenleeceramics/','St Ives','',''),
	('Emilie Shapiro','https://www.instagram.com/emilieshapirojewelry/','NYC','',''),
	('Yolish','https://www.instagram.com/yolish.designs/','Las Vegas','',''),
	('Merle Rosenbaum Lambeth','https://www.instagram.com/clayfolder/','San Diego','',''),
	('Laura Hatfield || Laura Makes','https://www.instagram.com/laura.makes/','','',''),
	('Hannah Shipway','https://www.instagram.com/jerichostudiopottery/','Oxford','',''),
	('Lisa Smirnova','https://www.instagram.com/lisa_smirnova/','Moscow','',''),
	('Andrzej Bero','https://www.instagram.com/andrzejbero/','Warszawa','',''),
	('Dai Li','https://www.instagram.com/dai_li_/','North Hobart','',''),
	('sinikka Harms','https://www.instagram.com/sinikkaharmsceramics/','Wriedel','',''),
	('Cassandra Fernandez','https://www.instagram.com/cassastamps/','Barcelona','',''),
	('Taran CordonHill','https://www.instagram.com/brandnewterrainpottery/','Madison','',''),
	('Christo Giles','https://www.instagram.com/christogiles/','Cape Town','',''),
	('Public Holiday','https://www.instagram.com/itsapublicholiday/','Sydney','',''),
	('Origin Design','https://www.instagram.com/origindesignermarket/','Austin','',''),
	('The Makers Market','https://www.instagram.com/the.makers.market/','','',''),
	('Memphis Maker Market','https://www.instagram.com/memphismakermarket/','Memphis','',''),
	('Maricor/Maricar','https://www.instagram.com/maricormaricar/','','',''),
	('Yasuko Tang','https://www.instagram.com/yasuko.arakawa/','London','',''),
	('Uh la la Ceramic Studio','https://www.instagram.com/uhlala_ceramics/','Copenhagen','',''),
	('mayumi yamashita','https://www.instagram.com/mayumiyamashitaceramics/','','',''),
	('MeyerLavigne','https://www.instagram.com/meyerlavigne/','Copenhagen','',''),
	('Charlotte Serup','https://www.instagram.com/charlotteserupkeramik/','Copenhagen','',''),
	('GRÖN','https://www.instagram.com/gronhandmadesp/','São Paulo','',''),
	('Espaço Autoral','https://www.instagram.com/espacoautoral/','Rio de Janeiro','',''),
	('Gina Zycher','https://www.instagram.com/glittermountain/','Los Angeles','',''),
	('Regina Middleton','https://www.instagram.com/reginamiddleton/','Torquay','',''),
	('Lilo Ceramica','https://www.instagram.com/lilo.ceramica/','','',''),
	('InnerFinn','https://www.instagram.com/innerfinn/','','',''),
	('Isobel Higley','https://www.instagram.com/isobelhigley/','','',''),
	('Michael Rice','https://www.instagram.com/michaelriceceramics/','Dubai','',''),
	('MELBOURNE SOAPWORKS','https://www.instagram.com/melbournesoapworks/','Melbourne','',''),
	('Kelci Potter','https://www.instagram.com/kelcipotter/','','',''),
	('Kaitlyn Brennan','https://www.instagram.com/kaitlynabrennan/','Ottawa','',''),
	('Estudio Baleia','https://www.instagram.com/estudiobaleia/','','',''),
	('O-M OBJECT-MATTER CERAMIC','https://www.instagram.com/omceramic/','Los Angeles','',''),
	('Seed Store','https://www.instagram.com/seedstore/','San Francisco','',''),
	('Bazar da Praça','https://www.instagram.com/bazardapraca/','São Paulo','',''),
	('Satya Ceramics','https://www.instagram.com/satyaceramics/','Bangalow','',''),
	('Pivo','https://www.instagram.com/na.pivo/','São Paulo','',''),
	('Objeto Cerâmico','https://www.instagram.com/objetoceramico/','São Paulo','',''),
	('The Clay Lab','https://www.instagram.com/theclaylabmalmo/','Malmö','',''),
	('Terre Ferme Pottery','https://www.instagram.com/terrefermepottery/','St Albert','',''),
	('Galpão 85','https://www.instagram.com/galpao85/','São Paulo','',''),
	('Porta Preta','https://www.instagram.com/portapreta.ateliegrafico/','Rio de Janeiro','',''),
	('Volta OC','https://www.instagram.com/voltaoficinacriativa/','Lisboa','',''),
	('Taller Mezcolanza Creativa','https://www.instagram.com/taller_mezcolanza_creativa/','Santiago','',''),
	('Dai Bags','https://www.instagram.com/daibags/','São Paulo ?','',''),
	('Cameoko','https://www.instagram.com/cameoko_jewelry/','Atlanta','',''),
	('Mush','https://www.instagram.com/m_u_s_h/','','',''),
	('Pip Wilcox','https://www.instagram.com/pipwilcoxceramics/','Hastings','',''),
	('Debbie Nicholls','https://www.instagram.com/debbie_in_london/','London','',''),
	('Suze','https://www.instagram.com/suze___________/','?','',''),
	('ＤＩＮＡ ＮＵＲ','https://www.instagram.com/nur_ceramics/','NYC','',''),
	('Micah Hamilton','https://www.instagram.com/micah.hamilton/','Oklahoma City','',''),
	('Question the answer','https://www.instagram.com/questntheanswr/','Memphis','',''),
	('Rural Kind','https://www.instagram.com/ruralkind/','Wales','',''),
	('Kaliko Shop','https://www.instagram.com/kaliko.shop/','Berlin','',''),
	('Demeter Cerâmicas','https://www.instagram.com/demeterceramicas/','São Paulo','',''),
	('The Crafters Box','https://www.instagram.com/thecraftersbox/','','',''),
	('Sodo Flea','https://www.instagram.com/sodoflea/','Seattle','',''),
	('Amanda Ramos Jóias','https://www.instagram.com/amandaramosjoias/','Campina Grande','',''),
	('Liê','https://www.instagram.com/joiaslie/','São Paulo','',''),
	('Spako Clay','https://www.instagram.com/spakoclay/','Austin','',''),
	('Lavanda','https://www.instagram.com/lavanda.co/','Porto Alegre','',''),
	('Gypso','https://www.instagram.com/ola.gypso/','São Paulo','',''),
	('Caelum Cerâmicas','https://www.instagram.com/caelumceramicas/','Rio de Janeiro','',''),
	('Studio 2','https://www.instagram.com/studio2.hamburg/','Hamburg','',''),
	('Shopf Papier','https://www.instagram.com/schopfpapier/','Rio de Janeiro','',''),
	('Lebú','https://www.instagram.com/_lebu/','São Paulo','',''),
	('Mariana Moysés','https://www.instagram.com/mariana_moyses/','Rio de Janeiro','',''),
	('Lela Cerâmicas','https://www.instagram.com/lela.ceramicas/','?','',''),
	('Yara Fukimoto','https://www.instagram.com/yarafukimoto/','São Paulo','',''),
	('Bádue Modelados','https://www.instagram.com/badue_modelados/','São Paulo','',''),
	('Tori no Su . Cerâmica','https://www.instagram.com/tori.no.su.ceramica/','','',''),
	('Estudio Boitatá','https://www.instagram.com/estudioboitata/','Campo Largo','',''),
	('Cabeçudinhos','https://www.instagram.com/cabecudinhos/','Sorocaba','',''),
	('Alma Objetos Cerâmicos','https://www.instagram.com/alma.objetos.ceramicos/','Porto Alegre','',''),
	('SUD','https://www.instagram.com/holasud/','','',''),
	('EnTorno','https://www.instagram.com/entornoceramica/','Curitiba','',''),
	('Anna Charlie','https://www.instagram.com/anna.charlie/','São Paulo','',''),
	('Helen Levi','https://www.instagram.com/helen_levi/','NYC','',''),
	('Flor de Leonardis','https://www.instagram.com/flordeleonardis/','','',''),
	('Lena Muniz','https://www.instagram.com/lenamuniz1/','Curitiba','',''),
	('Moio Studio','https://www.instagram.com/moio.studio/','Berlin','',''),
	('Katie Marks','https://www.instagram.com/anotherseattleartist/','Seattle','',''),
	('Projeto Curadoria','https://www.instagram.com/projetocuradoria/','','',''),
	('Atelie Kianda','https://www.instagram.com/ateliekianda/','São Gonçalo','',''),
	('Cindy Labrecque','https://www.instagram.com/cindy.labrecque/','','',''),
	('Eloísa Froes','https://www.instagram.com/eloisafroes/','Rio de Janeiro','',''),
	('Jolana Pineda','https://www.instagram.com/jolanapinedaceramics/','Pasadena','',''),
	('Woonwinkel','https://www.instagram.com/woonwinkel/','Portland','',''),
	('Alex Simon','https://www.instagram.com/makegoodchoices/','Portland','',''),
	('Naomi Singer - Modern Mud','https://www.instagram.com/modernmud_ceramics/','','',''),
	('Pluri','https://www.instagram.com/pluriarq/','Rio de Janeiro','',''),
	('Thais Mor atelier','https://www.instagram.com/thaismor_atelier/','São Paulo','',''),
	('Criativo Mutuá','https://www.instagram.com/criativo_mutua/','Rio de Janeiro','',''),
	('Riscô Art','https://www.instagram.com/risco_art/','Rio de Janeiro','',''),
	('Marla Rabelo','https://www.instagram.com/marlarabelo/','Rio de Janeiro','',''),
	('sissy moon','https://www.instagram.com/sissy.moon/','Portland','',''),
	('Propped','https://propped.com/maker-list','','',''),
	('COMMUNE BONDI','https://www.instagram.com/commune_bondi/','','',''),
	('Carolina Peraça','https://www.instagram.com/carolinaperaca/','São Paulo','',''),
	('Marla Benton','https://www.instagram.com/marla.benton/','Mahone Bay','',''),
	('Brookwood Pottery','https://www.instagram.com/brookwood_pottery/','Dublin','',''),
	('Casa Jupiter','https://www.instagram.com/casajupiter_woodwork/','São Paulo','',''),
	('Elise Rolot','https://www.instagram.com/elise.rolot/','Berlin','',''),
	('Ziovara','https://www.instagram.com/ziovara/','São Paulo ?','',''),
	('Atelie B','https://www.instagram.com/atelierbmtl','Montreal','',''),
	('Jen Fontanella','https://www.instagram.com/artbyjenf/','Overland Park','',''),
	('Lesley McInally Ceramics','https://www.instagram.com/lesleymcinallyceramics/','','',''),
	('Mii','https://www.instagram.com/miiatelier/','São Paulo','',''),
	('Arjan Van Dal','https://www.instagram.com/arjanvandal_ceramics/','??','',''),
	('Tamara Sandoul','https://www.instagram.com/ldnpotco/','London','',''),
	('Tarragon Smith','https://www.instagram.com/tarragonsmith/','London','',''),
	('Kin Leung','https://www.instagram.com/kinleung23/','London','',''),
	('Azem William Ceramics','https://www.instagram.com/ceramicazem/','London','',''),
	('Common Objects','https://www.instagram.com/commonobjects.studio/','London','',''),
	('Ida Riveros','https://www.instagram.com/riveida/','London','',''),
	('Ditte Blohm','https://www.instagram.com/blohm_ceramics/','London','',''),
	('Ayse Habibe Kucuk','https://www.instagram.com/aysehabibekucuk/','London','',''),
	('Silvo! Design','https://www.instagram.com/o_silvo/','Rio de Janeiro','',''),
	('Modern Craft Workshop','https://www.instagram.com/_rebeccaproctor/','North Cornwall','',''),
	('Rosmond Pottery','https://www.instagram.com/rosmond_pottery/','NYC','',''),
	('Porcelume','https://www.instagram.com/porcelume/','Melbourne','',''),
	('Feira Calor','https://www.instagram.com/feiracalor/','São Paulo','',''),
	('Omelet Trees Studio','https://www.instagram.com/omelettrees.studio/','','',''),
	('Ghost Wares','https://www.instagram.com/ghostwares/','Melbourne','',''),
	('E F Davies','https://www.instagram.com/e.f.davies.clay/','London','',''),
	('Ceramics 274','https://www.instagram.com/ceramics274/','London','',''),
	('Pot Artefatos','https://www.instagram.com/pot.artefatos/','São Paulo','',''),
	('Jo Hoban','https://www.instagram.com/jojohoban/','Brisbane','',''),
	('Daisy Cooper Ceramics','https://www.instagram.com/daisycooperceramics/','Melbourne','',''),
	('Finders Keepers','https://www.instagram.com/finders_keepers/','','',''),
	('Sarah Koschak','https://www.instagram.com/sarahkoschak_ceramics/','','',''),
	('goodlyGOLD','https://www.instagram.com/goodlygold/','Melbourne','',''),
	('Amy Leeworthy','https://www.instagram.com/amyleeworthy/','Melbourne','',''),
	('Jen Betty','https://www.instagram.com/jenbettyeverett/','','',''),
	('Yesha Macdonald','https://www.instagram.com/yeshamac/','Melbourne','',''),
	('C. Albrecht','https://www.instagram.com/alb.ceramique/','','',''),
	('Pano','https://www.instagram.com/queroumpano/','Rio de Janeiro','',''),
	('souleve','https://www.instagram.com/soulevedesign/','São Paulo','',''),
	('Galeria Moinho','https://www.instagram.com/moinho.galeria/','Recife','',''),
	('Zezé Estúdio','https://www.instagram.com/zeze.estudio/','Recife','',''),
	('Caos Criação','https://www.instagram.com/caoscriacao/','Recife','',''),
	('3RD LADY','https://www.instagram.com/3rdlady/','BRISBANE','',''),
	('Alea atelier','https://www.instagram.com/aleaatelier/','Rio de Janeiro','',''),
	('Carol Tsai','https://www.instagram.com/ceramica_carol_tsai/','Ubatuba','',''),
	('Kumalu Cerâmica','https://www.instagram.com/kumalu_ceramica/','São Paulo','',''),
	('Ashes & Gravel','https://www.instagram.com/ashesandgravel/','?','',''),
	('Casa Dobra','https://www.instagram.com/casadobra/','São Paulo','',''),
	('Ceramics Daily','https://www.instagram.com/ceramics.daily/','','',''),
	('Evna','https://www.instagram.com/_evna/','?','',''),
	('Baú da Kio','https://www.instagram.com/baudakio/','Rio de Janeiro','',''),
	('Estúdio Ripa','https://www.instagram.com/estudio.ripa/','Rio de Janeiro','',''),
	('Renata Miwa','https://www.instagram.com/renatamiwa/','São Paulo','',''),
	('Cerâmicas da Cris','https://www.instagram.com/ceramicasdacris/','São Paulo','',''),
	('Jessica Funaro Cerâmicas','https://www.instagram.com/jessicafunaro/','Sorocaba','',''),
	('Alice Lobato','https://www.instagram.com/alicelobatojoias/','Rio de Janeiro','',''),
	('Helebora','https://www.instagram.com/helebora_/','São Paulo ?','',''),
	('AWK Clayworks','https://www.instagram.com/awk_clayworks/','Boulder','',''),
	('White Fox Studio','https://www.instagram.com/whitefoxstudio/','Austing','',''),
	('Caixa Cosmo','https://www.instagram.com/caixacosmo/','','',''),
	('Nous','https://www.instagram.com/nous_paris/','Paris','',''),
	('Tierra Sol Studio','https://www.instagram.com/tierrasolstudio/','Durham, NC','',''),
	('Rocha do Campo','https://www.instagram.com/rochadocampo/','?','',''),
	('Ayesha Aggarwal','https://www.instagram.com/ayeshaaggarwal/','Adelaide','',''),
	('Liquorice Moon Studios','https://www.instagram.com/liquorice_moon_studios/','Buderim','',''),
	('Circulo Ceramics','https://www.instagram.com/circulo.ceramics/','Lisboa','',''),
	('O Beija Flor','https://www.instagram.com/o_beijaflor/','Porto','',''),
	('Rachel Carter','https://www.instagram.com/rachelcarterceramics/','Auckland','',''),
	('MOSS by Mia M (@mosskeramik)','','','',''),
	('Daniela Salazar (@ddanielasalazar)','','','',''),
	('Emma Wood (@ewtex)','','','',''),
	('Encontro de Criadores (@encontrodecriadores)','','','',''),
	('anna westerlund (@annawesterlundceramics)','','','',''),
	('Munbeibi (@munbeibi)','','','',''),
	('Amanda Magrini (@magrini.amanda)','','','',''),
	('Estela Miazzi (@estelamiazzi)','','','',''),
	('Wet & Wood (@wetandwood)','','','',''),
	('Joias com madeira (@studioadrianavalente)','','','',''),
	('N O I G A - Acessórios (@_noiga)','','','',''),
	('Com Amor Florinda (@comamorflorinda)','','','',''),
	('ORTells dieses&jenes (@ortellsdiesesundjenes)','','','',''),
	('Janža (@janza_jnz)','','','',''),
	('Blogfabrik Berlin (@blogfabrik)','','','',''),
	('Casa Capaz (@casa_capaz)','','','',''),
	('Círculo Ceramics (@circulo.ceramics)','','','',''),
	('Studio Hertzberg (@studio_hertzberg_berlin)','','','',''),
	('f l u i d a (@feirafluida)','','','',''),
	('The Handmade Pop-Up (@thehandmadepopup)','','','',''),
	('APATO Copenhagen (@apatocopenhagen)','','','',''),
	('Casa Petra Atelie (@casa_petra)','','','',''),
	('Gabriel Bianchini (@sete.pele)','','','',''),
	('Z I O V A R A . C O M . B R (@ziovara)','','','',''),
	('Atelier Make (@ateliermake)','','','','');
