# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('MB', 'Maker or Brand'), ('EV', 'Event'), ('ST', 'Store'), ('SP', 'Space')], default='MB', max_length=100)),
            ],
        ),
    ]
