# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnm_guide', '0002_auto_20171103_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(blank=True, choices=[('MB', 'Maker or Brand'), ('EV', 'Event'), ('ST', 'Store'), ('SP', 'Space')], default='MB', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='local',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
